/* This App path */
export const apiUrl = process.env.URL;
export const subjects = "/api/subjects";
export const login = "/api/login";
export const renew = "/api/renew";
export const allSubjects = "/api/allSubjects";
export const openSubjectForEnroll = "/api/token/openSubjectForEnroll";
export const searchSectionDetail = "/api/token/searchSectionDetail";
export const getTableSubjectsDetail = "/api/token/getTableSubjectsDetail";
export const allGenEd = "/api/allGenEd";
export const getPlan = "/api/token/getPlan";
export const savePlan = "/api/token/savePlan";
export const checkGrades = "/api/token/checkGrades";
export const getStdPlan = "/api/token/getStdPlan";
export const getStdPlanStructure = "/api/token/getStdPlanStructure";
export const getStdEducation = "/api/token/getStdEducation";
export const getSchedule = "/api/token/getSchedule";
export const getListOfEnrollResult = "/api/token/getListOfEnrollResult";
export const searchSubjectOpenEnr = "/api/token/searchSubjectOpenEnr";

/* My KU path */
export const kuUrl = process.env.KU_URL;
export const kuOpenSubjectForEnroll = "/enroll/openSubjectForEnroll";
export const kuSearchSectionDetail = "/enroll/searchSectionDetail";
export const kuLogin = "/auth/login";
export const kuRenew = "/auth/renew";
export const kuCheckGrades = "/std-profile/checkGrades";
export const kuGetStdEducation = "/std-profile/getStdEducation";
export const kuGetschedule = "/common/getschedule";
export const kuSearchEnrollResult = "/enroll/searchEnrollResult";
export const kusearchSubjectOpenEnr = "/enroll/searchSubjectOpenEnr";
